### ISSUE TITLE
[Testing Party] Event list UI runs off the card

### ISSUE THREAD

**Issue by joeleu** [gcivil-nyu-org/INET-Monday-Spring2023-Team-1#228]
When creating an event with a long description the date gets pushed off of the card and into the space between cards.

<img width="565" alt="Screenshot 2023-04-13 at 20 06 49" src="https://user-images.githubusercontent.com/15133747/231909088-aee95f30-eb40-4aa0-bacd-8d5da142c6b0.png">

**Comment by aaqilkhoja** [comment]
Thanks for the feedback! Fixed.
